FROM haskell:TAG AS build
RUN cabal update && cabal install fourmolu-VERSION
RUN cp -L /root/.local/bin/fourmolu /root/fourmolu

FROM debian:latest
COPY --from=build /root/fourmolu /bin/fourmolu
RUN apt-get update && apt-get install -y git
ENTRYPOINT ["fourmolu"]
CMD ["--mode", "check"]
