---

name: Build docker-fourmolu image

on:
  workflow_call:
    inputs:
      haskell_tag:
        default: latest
        required: false
        type: string
      tag:
        default: latest
        required: false
        type: string
      version:
        default: 0.15.0.0
        required: false
        type: string
  workflow_dispatch:
    inputs:
      haskell_tag:
        default: latest
        description: Image tag to build from.
        required: true
        type: string
      tag:
        description: Image tag to publish to.
        required: false
        type: string
      version:
        default: 0.15.0.0
        description: Fourmolu version to build.
        required: true
        type: string

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make Dockerfile
        run: make -- TAG=${{ inputs.haskell_tag }} VERSION=${{ inputs.version }}
      - name: Access GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.${{ inputs.haskell_tag }}
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/\
            docker-fourmolu:${{ inputs.tag || inputs.haskell_tag }}"
