---

name: Build docker-fourmolu image

on:
  workflow_call:
    inputs:
      haskell_tag:
        default: latest
        required: false
        type: string
      tag:
        default: latest
        required: false
        type: string
      version:
        default: 0.14.0.0
        required: false
        type: string
  workflow_dispatch:
    inputs:
      haskell_tag:
        description: Image tag to build from.
        required: true
        type: string
        default: latest
      tag:
        description: Image tag to publish to.
        required: false
        type: string
      version:
        description: Fourmolu version to build.
        required: true
        type: string
        default: 0.14.0.0

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make Dockerfile
        run: make -- TAG=${{ inputs.haskell_tag }} VERSION=${{ inputs.version }}
      - name: Access GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.${{ inputs.haskell_tag }}
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/\
            docker-fourmolu:${{ inputs.tag || inputs.haskell_tag }}"
