---

name: Build docker-fourmolu:latest

on:
  push:
    branches:
      - main
  schedule:
    - cron: "15 23 * * 2"

jobs:
  build:
    name: Build docker-fourmolu:latest
    uses: danieljtrowbridge/docker-fourmolu/.github/workflows/build.yaml@main
